services:
  - type: web
    name: oviflow-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_BASE
        value: https://api.groq.com/openai/v1
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: FRONTEND_URL
        sync: false
