import { jsPDF } from "jspdf";
import type { CycleLog } from "../services/api";

interface PdfOptions {
  userName?: string;
  mode?: string;
  logs?: CycleLog[];
  cycleLength?: number;
  periodLength?: number;
}

export function generateCyclePDF(options: PdfOptions): Blob {
  const { userName = "Patient", mode = "cycle", logs = [], cycleLength = 28, periodLength = 5 } = options;
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // ── Header ──
  doc.setFillColor(219, 39, 119);
  doc.rect(0, 0, pageW, 38, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("OVIFLOW", 20, 18);
  doc.setFontSize(10);
  doc.text("Cycle Health Summary Report", 20, 26);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, 20, 33);

  // ── Patient Info ──
  let y = 50;
  doc.setTextColor(30, 27, 75);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Patient Information", 20, y); y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Name: ${userName}`, 20, y); y += 6;
  doc.text(`Mode: ${mode.charAt(0).toUpperCase() + mode.slice(1)}`, 20, y); y += 6;
  doc.text(`Cycle Length: ${cycleLength} days`, 20, y); y += 6;
  doc.text(`Period Length: ${periodLength} days`, 20, y); y += 12;

  // ── Cycle Statistics ──
  const periodDates = logs.filter((l) => l.isPeriod).map((l) => l.date);
  const moodCounts: Record<string, number> = {};
  const symptomCounts: Record<string, number> = {};
  let heavyDays = 0;

  for (const log of logs) {
    if (log.mood) moodCounts[log.mood] = (moodCounts[log.mood] || 0) + 1;
    if (log.flow === "heavy") heavyDays++;
    for (const s of log.symptoms) {
      symptomCounts[s] = (symptomCounts[s] || 0) + 1;
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary Statistics", 20, y); y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Total logs recorded: ${logs.length}`, 20, y); y += 6;
  doc.text(`Period days logged: ${periodDates.length}`, 20, y); y += 6;
  doc.text(`Heavy flow days: ${heavyDays}`, 20, y); y += 6;

  // Top moods
  const topMoods = Object.entries(moodCounts).sort((a, b) => b[1] - a[1]).slice(0, 3);
  if (topMoods.length > 0) {
    doc.text(`Most common moods: ${topMoods.map(([m, c]) => `${m} (${c}x)`).join(", ")}`, 20, y); y += 6;
  }

  // Top symptoms
  const topSymptoms = Object.entries(symptomCounts).sort((a, b) => b[1] - a[1]).slice(0, 5);
  if (topSymptoms.length > 0) {
    doc.text(`Top symptoms: ${topSymptoms.map(([s, c]) => `${s} (${c}x)`).join(", ")}`, 20, y); y += 6;
  }
  y += 8;

  // ── Log Table ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Recent Log History", 20, y); y += 8;

  // Table header
  doc.setFillColor(243, 232, 255);
  doc.rect(18, y - 4, pageW - 36, 8, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("Date", 20, y);
  doc.text("Period", 52, y);
  doc.text("Flow", 72, y);
  doc.text("Mood", 92, y);
  doc.text("Symptoms", 118, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  const recentLogs = logs.slice(0, 30);
  for (const log of recentLogs) {
    if (y > 275) { doc.addPage(); y = 20; }
    // Alternate row bg
    if (recentLogs.indexOf(log) % 2 === 0) {
      doc.setFillColor(250, 245, 255);
      doc.rect(18, y - 4, pageW - 36, 7, "F");
    }
    doc.setFontSize(8);
    doc.text(log.date, 20, y);
    doc.text(log.isPeriod ? "Yes" : "-", 52, y);
    doc.text(log.flow || "-", 72, y);
    doc.text(log.mood || "-", 92, y);
    const sympText = log.symptoms.length > 0 ? log.symptoms.slice(0, 3).join(", ") : "-";
    doc.text(sympText, 118, y);
    y += 7;
  }
  y += 8;

  // ── Concerns ──
  const concerns = generateConcerns(logs);
  if (concerns.length > 0) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(220, 38, 38);
    doc.text("⚠ Flagged Concerns", 20, y); y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 27, 75);
    for (const c of concerns) {
      if (y > 275) { doc.addPage(); y = 20; }
      doc.text(`• ${c}`, 22, y); y += 6;
    }
    y += 6;
  }

  // ── Footer ──
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by OVIFLOW — This is not a medical diagnosis.", 20, 288);
    doc.text(`Page ${i} of ${pageCount}`, pageW - 40, 288);
  }

  return doc.output("blob");
}

function generateConcerns(logs: CycleLog[]): string[] {
  const concerns: string[] = [];
  if (logs.length < 3) return concerns;

  const periodDates = logs.filter((l) => l.isPeriod).map((l) => new Date(l.date).getTime()).sort((a, b) => b - a);
  if (periodDates.length >= 3) {
    const gaps: number[] = [];
    for (let i = 0; i < periodDates.length - 1; i++) {
      gaps.push(Math.round((periodDates[i] - periodDates[i + 1]) / (1000 * 60 * 60 * 24)));
    }
    const validGaps = gaps.filter((g) => g > 15 && g < 60);
    if (validGaps.length >= 2) {
      const avg = validGaps.reduce((a, b) => a + b, 0) / validGaps.length;
      const lastGap = validGaps[0];
      if (Math.abs(lastGap - avg) > 7) {
        concerns.push(`Last cycle was ${lastGap} days (average: ${Math.round(avg)} days) — irregular`);
      }
    }
  }

  const recent = logs.slice(0, 14);
  const heavyDays = recent.filter((l) => l.flow === "heavy").length;
  if (heavyDays >= 4) concerns.push(`Heavy flow logged ${heavyDays} days in recent 2 weeks`);

  const lowMood = recent.filter((l) => l.mood === "low" || l.mood === "anxious").length;
  if (lowMood >= 5) concerns.push(`Low/anxious mood ${lowMood} of last ${recent.length} days`);

  return concerns;
}

export function downloadCyclePDF(options: PdfOptions): void {
  const blob = generateCyclePDF(options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `oviflow-summary-${new Date().toISOString().slice(0, 10)}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
